### ISSUE TITLE
`yarn` fails

### ISSUE THREAD

**Issue by stefan-mihaila** [LN-Juggernaut/juggernaut-desktop#7]
## Prerequisites

- [x] Using yarn
- [ ] Using node 10.x
- [x ] Using an up-to-date [`master` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/master)
- [ ] Using latest version of devtools. See [wiki for howto update](https://github.com/electron-react-boilerplate/electron-react-boilerplate/wiki/DevTools)
- [ ] Link to stacktrace in a Gist (for bugs)
- [ ] For issue in production release, devtools output of `DEBUG_PROD=true yarn build && yarn start`
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)

## Expected Behavior

`yarn` installs deps

## Current Behavior

```
yarn
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
$ yarn build-dll && electron-builder install-app-deps
yarn run v1.22.4
$ webpack -r @babel/register --config webpack/webpack.config.dll.js
/Users/cypherpunk/juggernaut-desktop/node_modules/webpack-cli/bin/cli.js:93
				throw err;
				^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /Users/cypherpunk/juggernaut-desktop/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:524:9)
    at resolveExports (internal/modules/cjs/loader.js:541:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:661:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:963:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/cypherpunk/juggernaut-desktop/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/cypherpunk/juggernaut-desktop/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (/Users/cypherpunk/juggernaut-desktop/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/Users/cypherpunk/juggernaut-desktop/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.newLoader [as .js] (/Users/cypherpunk/juggernaut-desktop/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/cypherpunk/juggernaut-desktop/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/cypherpunk/juggernaut-desktop/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (/Users/cypherpunk/juggernaut-desktop/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._compile (/Users/cypherpunk/juggernaut-desktop/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Object.newLoader [as .js] (/Users/cypherpunk/juggernaut-desktop/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (/Users/cypherpunk/juggernaut-desktop/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at requireModule (/Users/cypherpunk/juggernaut-desktop/node_modules/@babel/core/lib/config/files/plugins.js:165:12)
    at loadPreset (/Users/cypherpunk/juggernaut-desktop/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
    at createDescriptor (/Users/cypherpunk/juggernaut-desktop/node_modules/@babel/core/lib/config/config-descriptors.js:154:9)
    at /Users/cypherpunk/juggernaut-desktop/node_modules/@babel/core/lib/config/config-descriptors.js:109:50
    at Array.map (<anonymous>) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

## Steps to Reproduce (for bugs)

1. git clone

2. cd

3. yarn

4.

## Your Environment

- Node version : v13.12.0
- Version or Branch used : master
- Operating System and version : MacOS Catalina
- Link to your project :

**Comment by johncantrell97** [comment]
can you try using node 13.3? That's what I've been using for development

**Comment by stefan-mihaila** [comment]
using node 13.3 fixes it
